let temp_match_data = [
    {
        id: 72005, 
        data: {
            "left_team_image": "https://s3.ap-south-1.amazonaws.com/myteam11main/images/teamflags/CK_DEL_6.png",
            "left_team_name": "DEL",
            "left_team_players": [
                {
                "credits": 9,
                "name": "Prithvi Shaw",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/11478-IPL.png",
                "player_fixed_id": 36,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 91.11,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 0
            }, {
                "credits": 8,
                "name": "Kamlesh Nagarkoti",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/11534-IPL.png",
                "player_fixed_id": 59,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 1
            }, {
                "credits": 8.5,
                "name": "Shardul Thakur",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/2104-IPL.png",
                "player_fixed_id": 626,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 52,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 2
            }, {
                "credits": 9.5,
                "name": "Rishabh Pant",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/8993-IPL.png",
                "player_fixed_id": 632,
                "playing": 0,
                "points": 0,
                "role": 0,
                "selected_by": 89.33,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 3
            }, {
                "credits": 8.5,
                "name": "Axar Patel",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1519-IPL.png",
                "player_fixed_id": 634,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 31.29,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 4
            }, {
                "credits": 7.5,
                "name": "Pravin Dubey",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/6807-IPL.png",
                "player_fixed_id": 903,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.09,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 5
            }, {
                "credits": 7.5,
                "name": "Ashwin Hebbar",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/8852-IPL.png",
                "player_fixed_id": 913,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 0.18,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 6
            }, {
                "credits": 8,
                "name": "Kona Srikar-Bharat",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/5978-IPL.png",
                "player_fixed_id": 933,
                "playing": 0,
                "points": 0,
                "role": 0,
                "selected_by": 0.18,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 7
            }, {
                "credits": 8.5,
                "name": "Chetan Sakariya",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/15056-IPL.png",
                "player_fixed_id": 1232,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.09,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 8
            }, {
                "credits": 8.5,
                "name": "Mitchell Marsh",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/942-IPL.png",
                "player_fixed_id": 1297,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 20.71,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 9
            }, {
                "credits": 8,
                "name": "Tim Seifert",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1918-IPL.png",
                "player_fixed_id": 1493,
                "playing": 0,
                "points": 0,
                "role": 0,
                "selected_by": 0.44,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 10
            }, {
                "credits": 10,
                "name": "David Warner",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/119-IPL.png",
                "player_fixed_id": 1546,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 94.13,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 11
            }, {
                "credits": 8.5,
                "name": "Anrich Nortje",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/12081-IPL.png",
                "player_fixed_id": 1561,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.44,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 12
            }, {
                "credits": 8.5,
                "name": "Mustafizur Rahman",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/opta-cricket/1843.png",
                "player_fixed_id": 1599,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 12.71,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 13
            }, {
                "credits": 8,
                "name": "Sarfaraz Khan",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1495-IPL.png",
                "player_fixed_id": 1617,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 0.62,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 14
            }, {
                "credits": 9,
                "name": "Kuldeep Yadav",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1889-IPL.png",
                "player_fixed_id": 1623,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 87.02,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 15
            },
            {
                "credits": 8,
                "name": "Lalit Yadav",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/11590-IPL.png",
                "player_fixed_id": 4417,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 14.58,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 16
            }, {
                "credits": 8,
                "name": "Lungi Ngidi",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/opta-cricket/8506.png",
                "player_fixed_id": 4748,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.09,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 17
            }, {
                "credits": 8.5,
                "name": "Khaleel Ahmed",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/9164-IPL.png",
                "player_fixed_id": 4838,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 39.64,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 18
            }, {
                "credits": 8,
                "name": "Rovman Powell",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/9969-IPL.png",
                "player_fixed_id": 4872,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 6.84,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 19
            }, {
                "credits": 7.5,
                "name": "Ripal Patel",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/27213-IPL.png",
                "player_fixed_id": 24410,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 0.09,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 20
            }, {
                "credits": 8,
                "name": "Yash Dhull",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/default-player-image.png",
                "player_fixed_id": 25710,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 0.18,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 21
            }, {
                "credits": 8.5,
                "name": "Mandeep Singh",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/opta-cricket/47345.png",
                "player_fixed_id": 47736,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 0,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 22
            }, {
                "credits": 7.5,
                "name": "Vicky Ostwal",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/default-player-image.png",
                "player_fixed_id": 89743,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0,
                "team_name": "DEL",
                "team_index": 0,
                "player_index": 23
            }
        ],
            "lineup_status": 0,
            "match_time": "2022-04-20T14:00:00+00:00",
            "right_team_image": "https://s3.ap-south-1.amazonaws.com/myteam11main/images/teamflags/CK_PUN_1.png",
            "right_team_name": "PUN",
            "right_team_players": 	[
                {
                "credits": 8,
                "name": "Shahrukh Khan",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/8998-IPL.png",
                "player_fixed_id": 471,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 9.96,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 24
            }, {
                "credits": 7.5,
                "name": "Benny Howell",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/2126-IPL.png",
                "player_fixed_id": 537,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 0.09,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 25
            }, {
                "credits": 8.5,
                "name": "Kagiso Rabada",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1979-IPL.png",
                "player_fixed_id": 648,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 90.04,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 26
            }, {
                "credits": 9,
                "name": "Mayank Agarwal",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1137-IPL.png",
                "player_fixed_id": 898,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 41.16,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 27
            }, {
                "credits": 7.5,
                "name": "Prerak Mankad",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/11561-IPL.png",
                "player_fixed_id": 1260,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 0.18,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 28
            }, {
                "credits": 8.5,
                "name": "Arshdeep Singh",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/15170-IPL.png",
                "player_fixed_id": 1499,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 7.73,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 29
            }, {
                "credits": 8,
                "name": "Ishan Porel",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/11097-IPL.png",
                "player_fixed_id": 1500,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.09,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 30
            }, {
                "credits": 8,
                "name": "Rishi Dhawan",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/716-IPL.png",
                "player_fixed_id": 1643,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 0.18,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 31
            }, {
                "credits": 8.5,
                "name": " J Sharma",
                "image ": "https: //d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/8702-IPL.png",
                "player_fixed_id": 2324,
                "playing": 0,
                "points": 0,
                "role": 0,
                "selected_by": 19.73,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 32
            }, {
                "credits": 7.5,
                "name": "Baltej Singh",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/9054-IPL.png",
                "player_fixed_id": 2333,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.09,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 33
            }, {
                "credits": 8.5,
                "name": "Sandeep Sharma",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1517-IPL.png",
                "player_fixed_id": 2337,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.09,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 34
            }, {
                "credits": 7.5,
                "name": "Writtick Chatterjee",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/11102-IPL.png",
                "player_fixed_id": 2669,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 0.18,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 35
            }, {
                "credits": 8.5,
                "name": "Odean Smith",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/9292-IPL.png",
                "player_fixed_id": 4634,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 45.6,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 36
            }, {
                "credits": 9.5,
                "name": "Shikhar Dhawan",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/646-IPL.png",
                "player_fixed_id": 4972,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 94.67,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 37
            }, {
                "credits": 8.5,
                "name": "Bhanuka Rajapaksa",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1307-IPL.png",
                "player_fixed_id": 5080,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 0.98,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 38
            }, {
                "credits": 7.5,
                "name": "Atharva Taide",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/14112-IPL.png",
                "player_fixed_id": 8027,
                "playing": 0,
                "points": 0,
                "role": 1,
                "selected_by": 0.18,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 39
            }, {
                "credits": 7.5,
                "name": "Prabhsimran Singh",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/18522-IPL.png",
                "player_fixed_id": 11933,
                "playing": 0,
                "points": 0,
                "role": 0,
                "selected_by": 5.78,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 40
            }, {
                "credits": 8,
                "name": "Harpreet Brar",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/21313-IPL.png",
                "player_fixed_id": 16629,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.09,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 41
            }, {
                "credits": 8,
                "name": "Nathan Ellis",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/opta-cricket/18727.png",
                "player_fixed_id": 23994,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 42
            }, {
                "credits": 8,
                "name": "Vaibhav Arora",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/29443-IPL.png",
                "player_fixed_id": 26499,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 2.31,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 43
            }, {
                "credits": 7.5,
                "name": "Ansh Patel",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/58449-IPL.png",
                "player_fixed_id": 59034,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 0.09,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 44
            }, {
                "credits": 8,
                "name": "Rajangad Bawa",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/83314-IPL.png",
                "player_fixed_id": 97113,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 0.09,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 45
            }, {
                "credits": 9,
                "name": "Rahul Chahar",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/11528-IPL.png",
                "player_fixed_id": 49,
                "playing": 0,
                "points": 0,
                "role": 3,
                "selected_by": 79.11,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 46
            }, {
                "credits": 10,
                "name": "Liam Livingstone",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/2288-IPL.png",
                "player_fixed_id": 203,
                "playing": 0,
                "points": 0,
                "role": 2,
                "selected_by": 95.38,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 47
            }, {
                "credits": 9,
                "name": "Jonny Bairstow",
                "image": "https://d13ir53smqqeyp.cloudfront.net/player-images/partner-image/IPL22/1189-IPL.png",
                "player_fixed_id": 374,
                "playing": 0,
                "points": 0,
                "role": 0,
                "selected_by": 65.42,
                "team_name": "PUN",
                "team_index": 1,
                "player_index": 48
            }],
            "sport_index": 0
        }
    }
]


export default temp_match_data;